# Travis CI configuration file for running tests
sudo: false
language: python
branches:
    only:
      - master
python:
  - "2.7"
install:
  - pip install -r test-requirements.txt
script:
  - pep8 .
  - pylint travis/
  - pytest --cov-report term-missing --cov=jenkins jenkins
  - pytest --cov-report term-missing --cov=aws aws
  - pytest --cov-report term-missing --cov=mobile_app mobile_app
  - pytest --cov-report term-missing --cov=travis travis
  - pytest --cov-report term-missing --cov=lambdas lambdas
