# Travis CI configuration file for running tests
language: python
branches:
    only:
      - master
python:
  - "2.7"
install:
  - pip install -r test-requirements.txt
script:
  - pep8 .
  - nosetests jenkins -v --with-coverage --cover-package=jenkins
  - nosetests aws -v --with-coverage --cover-package=aws
